name: panvimdoc

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_doc:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: user-notes
          pandoc: doc/user-notes.md
          treesitter: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(🤖): Auto generate docs"
          push_options: '--force-with-lease'
